ssafy6-nathan/algorithm-study

22.03.01/HJJ/Baekjoon1012.java, 22.03.01/HJJ/Baekjoon17086.java, 22.03.01/HJJ/Baekjoon9241.java
아기상어2, 유기농배추, 바이러스 복제 문제풀이 업로드
=> 황정준 문제풀이 업로드

22.03.01/HJH/b1012_유기농배추.java, 22.03.01/HJH/b17086_아기상어2.java, 22.03.01/HJH/b17086_아기상어2_메모리초과.java, 22.03.01/HJH/b17086_아기상어2_메모리초과2.java
바이러스 복제 못 풀었는데 다음부턴 어려운 문제 끄적인거라도 올려볼게요..
=> 한지희 문제풀이 업로드

22.03.01/HHS/Main_BOJ_1012_유기농배추.java, 22.03.01/HHS/Main_BOJ_17086_아기상어2.java
=> 한혜성 문제풀이 업로드

22.03.01/EJH/1주차/1012.py, 22.03.01/EJH/1주차/17086.py, 22.03.01/EJH/1주차/9241.py
=> 이정훈 문제풀이 업로드

22.03.08/HHS/Main_BOJ_17609_회문.java, 22.03.08/HHS/Main_BOJ_2156_포도주시식.java, 22.03.08/HHS/Main_BOJ_2579_계단오르기.java
**사회망 서비스 (SNS)** 문제에 대해서 어떻게 풀어야 할지 생각을 해봤는데
union find를 쓰고 dp를 이용하면 되지 않을까 하는 생각이 있지만 감이 제대로 잡히지 않아서
결국엔 풀지 못했숩니다 😥
=> 한혜성 알고리즘 문제풀이

22.03.15/HHS/Main_BOJ_2206_벽부수고이동하기.java, 22.03.15/HHS/Main_BOJ_2447_별찍기.java, 22.03.15/HHS/Main_BOJ_2805_나무자르기.java
별찍기는 시간초과가 났고...
나무 자르기는 반례들도 몇개 찾아서 넣어봤는데 답 다 나오는데,,,왜 틀렸다고 나오죠,,,
이번주 문제풀이,,,Whyrano..
=> [한혜성] 문제풀이 업로드

22.03.22/EJH/16562.py, 22.03.22/EJH/1956_1.py, 22.03.22/EJH/1956_2.py, 22.03.22/EJH/2667.py, 22.03.22/EJH/9935.py
- 1956_1 플로이드 와샬 풀이 pypy3는 통과 python 시간초과
- 1956_2 다익스트라 알고리즘 풀이 python 통과
=> 이정훈 알고리즘 문제풀이 업로드

22.04.05/HJJ/Programmers_GoldAndSilverCarry.java, 22.04.05/HJJ/Programmers_LightPathCycle.java, 22.04.05/HJJ/Programmers_NumPlus.java
4번 문제는 너무 어렵네요...
3번까지만 풀었습니다.
=> 황정준 알고리즘 문제풀이

22.04.05/EJH/gold_silver.py, 22.04.05/EJH/ligth_cycle.py, 22.04.05/EJH/no_number.py
=> 이정훈 5주차 문제풀이

22.04.05/HJH/b2075_N번째큰수.java
=> 한지희 알고리즘 문제풀이

22.05.10/SYB/2178. 미로 탐색/미로 탐색.py, 22.05.10/SYB/2468. 안전 영역/안전 영역.py, 22.05.10/SYB/2606. 바이러스/바이러스.py
=> 손영배 0510 문제풀이

22.06.07/HHS/Main_BOJ_14244_트리만들기.java, 22.06.07/HHS/Main_BOJ_9372_상근이의여행.java, 22.06.07/HHS/Main_BOJ_9934_완전이진트리.java
완전이진트리 문제에서 출력방식을 어떻게 해야할지 고민하다가 
거의 처음으로 StringBuffer 써본거 같숩니다
트리문제인데 트리로 안푼 느낌인데 이게 맞는건가여...ㅠㅠ
=> 한혜성 알고리즘문제풀이

22.06.21/HHS/Main_BOJ_1759_암호만들기.java, 22.06.21/HHS/Main_BOJ_9020_골드바흐의추측.java
책 페이지 하는데 노가다만 계속 떠올라서 뇌 좀 삭히고 오늘 스터디 후에 바로 다시 풀어볼게유
=> 한혜성_알고리즘문제풀이

study/22.08.30/EJH/1063_킹.py, study/22.08.30/EJH/14391_종이 조각.py, study/22.08.30/EJH/2234_성곽.py, study/22.08.30/EJH/3085_사탕 게임.py
이번 주는 바빠서 한 문제 못 풀었네요.
노력해보겠지만 아마 못 풀 것 같습니다.
=> 이정훈 문제 풀이 업로드

study/22.10.11/BJM/BOJ_1157.java, study/22.10.11/BJM/BOJ_14425.java, study/22.10.11/BJM/BOJ_4949.java, study/22.10.11/BJM/BOJ_5430.java
=> 방지민 문제풀이 업로드

README.md
=> [Week33] 33주차 문제 업로드

study/22.10.18/EJH/1038_감소하는 수.py, study/22.10.18/EJH/14712_넴모넴모 (Easy).py, study/22.10.18/EJH/15649_N과 M (1).py, study/22.10.18/EJH/15652_N과 M (4).py
- python으로 하니깐 계속 시간 초과 나서 결국 pypy3으로 했네요 (쓸데없었던 시간낭비)
- 감소하는 수가 어느 범위까지 가능한지 생각을 많이 하게 됨
- 내가 백트레킹으로 푼게 맞나?
알고리즘에서 자주 사용되는 기본기의 풀이지만 백트레킹 중간 조건 설정은 역시 많이 생각하게 된다.
=> [Week32] 이정훈 문제풀이 업로드

study/22.10.18/BJM/BOJ_1038.java, study/22.10.18/BJM/BOJ_14712.java, study/22.10.18/BJM/BOJ_15648.java, study/22.10.18/BJM/BOJ_15652.java
작년 여름에 dfs쓰는 문제 몇 번 풀었었는데, 재귀 프로세스를 하도 오랜만에 보니까 그냥 전체적으로 문제들을 어떻게 풀어야 할지, 재귀하면 어떻게 코드가 진행되는지 감이 잘 안와서 어려웠습니다..~
특히 감소하는 수 문제는 처음에 문제 자체가 이해가 안가서 남의 블로그 엿보고 와서야 이해했음 ㅎ
이번주는 전부 잘 모르겠어서 구글링 쪼금많이..했습니다ㅠㅠ 일단 생각해보고 정 모르겠다 싶으면 해결방법 참고해서 의사코드로 대충 써보고 코드썼어요.
왜 이게 되지? 왜 이렇게 되지? 싶은 코드들은 손으로 디버깅 하면서 이해했습니당.
남들이 푼 거 보면 어떻게 이런 풀이 방법을 생각해내지? 싶기도 했고....
> 넴모넴모 네모라이팅 하고싶었음 희희
=> [Week32] 방지민 문제풀이 업로드

study/22.10.18/HJJ/Baekjoon15649.java, study/22.10.18/HJJ/Baekjoon15652.java
요즘 야근때문에 아직 문제를 다 못풀어봐서 시간이 될지 모르겠지만
다 풀면 작성하겠습니다. 😂
백트래킹 문제를 요즘 잘 안풀어서 감이 좀 떨어져있었는데 다시 감을 회복할 수 있는 한 주였습니다.
=> [Week32] 황정준 문제풀이 업로드

study/22.10.25/BJM/Programmers_12918.java, study/22.10.25/BJM/Programmers_17683.java, study/22.10.25/BJM/Programmers_59043.sql, study/22.10.25/BJM/Programmers_64064.java
1. 방금그곡
이 문제를 어렵게 하는 조건들.. (1) 반음처리 (2) 재생시간
물론 이 외에도 풀이방법을 여러번 고쳐서 푸는데 꽤나 시간이 걸렸습니다..
반음을 한 글자로 처리해야겠다는 생각을 전혀 못해서, 처음엔 포인터 변수를 따로 만들고 문자열 하나씩 읽으면서 확인을 했는데 메모리초과가 나는 문제도 있고, # 때문에 문자열 길이가 달라진다는 점도 고려해야했고...
그 밖에 최대재생시간 조건도 나중에 알았고, 재생시간 계산도 잘못해서 27번 테스트케이스에서 걸리고... 그냥 완전 총체적 난국이었음 이제까지 푼 문제들 중에 제일 오래걸린듯..ㅎ
2. 있없
sql 다뤄본지가 너무 오래돼서 예약어를 별명으로 넣어놓고선 질의문 완전 완벽한데 ?? 왜안돼;; 이러고 있었다네요.
3. 불량사용자
전혀 감을 못잡고있다가 그냥 포기하고 질문하기 눌러서 봤는데 대부분 dfs로 푸시더라구요....
근데 알았는데도 구체적인 프로세스가 잘 안떠올라서, 스터디 전까진 코드완성을 못할거 같아 일단 불량사용자 후보 판단 여부를 확인하는 코드만 작성해서 올려놓았습니다.. ㅎㅎㅎ. 나중에 수정해서 같이 머지하겠숩니당 ~.~
코테문제는 항상 풀 때마다 느끼지만.. 문제를 이해하는 것 부터가 고역이라고 생각합니다...
그리고 알고리즘이나 공식이 필요없는 단순 구현문제인데도 푸는데 시간이 꽤나 걸려서 ... 연습만이 살길이겠죠 ㅎㅎ.
=> [Week33] 방지민 문제풀이 업로드

study/22.11.01/HJH/단어 변환.java, study/22.11.01/HJH/베스트앨범.java
베스트 앨범... 우선 푼 곳 까지 올려두겠습니다..
`genreTotalCountHashMap`, `genres_ordered` 있는 그대로 적고 싶어서 이런 식으로 변수명을 정했는데 한두단어로 조합하고 간결한 이름이 고민됐어요.. 변수명이 길어지니 어떤 변수인지는 직관적으로 보이지만 코드가 길어져서 가독성이 떨어진다고 생각했습니다. 직관적이면서도 가독성 좋은 변수명에 대해서 더 알아봐야겠다는 생각이 들었습니다. 
pr이 다 올라오지 않았던 이유는 제가 다 못 풀었기 때문이었습니다.. (베스트 앨범부터 풀려고 잡고 있다가 안 풀려서요..)
문자열 다루는 게 아직은 익숙하지 않은 거 같아요..
4문제를 다 풀어보지 못한 것에 대한 아쉬움이 있어요.. 다 비슷한 난이도라고 생각해서 한 문제가 안 풀리니까 이것부터 풀어내야한다는 부담이 좀 있었습니다.. ㅜ
=> [Week34] 한지희 문제풀이 업로드

study/22.11.01/EJH/가장 긴 팰린드롬.py, study/22.11.01/EJH/단어 변환.py, study/22.11.01/EJH/문자열 압축.py, study/22.11.01/EJH/문자열 압축2.py, study/22.11.01/EJH/베스트앨범.py
- 줄어든 문자열 길이 계산하는 부분에서 좀 헤맸네요
- hash를 많이 쓰게 된 문제
- 처음 알고리즘을 짤 때 많이 고민됬습니다.
- 파이썬의 경우 역순을 간단하게 변경 할 수 있었는데 자바의 코드가 어떻게 될지 궁금하네요
=> [Week34] 이정훈 문제풀이 업로드

study/22.11.01/HHS/가장긴팰린드롬.java, study/22.11.01/HHS/단어변환.java, study/22.11.01/HHS/문자열압축.java, study/22.11.01/HHS/베스트앨범.java
**- 베스트 앨범**
- 맵에 넣은 것들을 다시 리스트로 꺼내서 정렬하는 방법을 알지 못해 구글의 힘으로 정렬하였다. 휴,,,간단한건데 왜 몰랐는지 ㅎ,,하나 배워갑니다 총총총
- 이번주 내내 코테와 면접으로 인해 풀 시간이 거의 없어서 일단 풀기라도 하자는 식으로 했더니 코드가 깔끔해보이지 않아서 아쉽습니다,,
=> [Week34] 한혜성 문제풀이 업로드

study/22.11.01/BJM/Programmers_43163.java, study/22.11.01/BJM/Programmers_60057.java
다 풀진 못했는데 ... 생각하던거만 적어놓을게요
- 베스트앨범
카테고리가 해시로 정해져있어서 해시맵을 쓰는 문제겠거니 생각은 했습니다 .. 일단 장르별 정렬에 쓸 해시맵 하나가 필요할 것 같고(정렬을 위해서는 장르이름이 key값이고 전체재생횟수가 value겠지요....!!) 고유번호와 각 노래의 재생횟수가 저장될 해시맵이  필요할 것 같습니다.. 정렬해서 상위 2개씩 출력을 해주면 되겠네 .. 라고생각은 하는데 어떻게 해야할지 잘 모르겠네요 .. ㅎㅎ;;
- 가장 긴 팰린드롬
이친구는 문제이해만 하고 건들진 못했어요..👍
프로그래머스 풀 땐 1레벨문제 하나만 넣어주세요..................................💙
=> [Week34] 방지민 문제풀이 업로드

study/22.11.01/PKB/가장 긴 팰린드롬.java, study/22.11.01/PKB/단어 변환.java, study/22.11.01/PKB/문자열 압축.java, study/22.11.01/PKB/베스트앨범.java
전부다 어려웠어요..
베스트앨범도 그렇고 팰린드롬도 그렇고 어떻게 하면 되겠지 싶은데 코드로 구현해내는 게 어렵네요 ,,
문자열 끊임없이 연습해야겠어요 ㅎㅎㅎ
=> [Week34] 박기범 문제풀이 업로드

study/22.11.08/EJH/11725_트리의 부모.py, study/22.11.08/EJH/13116_30번.py, study/22.11.08/EJH/20364_부동산 다툼.py, study/22.11.08/EJH/5639_이진 검색 트리.py
- 입력 받는 게 끊어 지는 부분이 없어서 어떻게 입력 받는지는 찾아서 했습니다.
- 전위 순회를 후위 순회로 바꾸는 방식을 많이 생각 하게 되었습니다.
오랜만의 그래프인지라 많이 헷갈렸네요. 그래프 접근 방식을 많이 해봐야겠습니다.
=> [Week35] 이정훈 문제풀이 업로드

study/22.11.08/PKB/30번.java, study/22.11.08/PKB/부동산 다툼.java, study/22.11.08/PKB/이진 검색 트리.java, study/22.11.08/PKB/트리의 부모 찾기.java
- 저는 트리를 만들어서 했는데 점화식으로 푸는 방법도 있더라고요. 봐도 어렵던데 그런 생각은 어떻게 해내는 걸까요 ,,
트리 문제를 거의 안 풀어봤어서 처음에 인접리스트 이런 거 찾아보면서 했습니다..
=> [Week35] 박기범 문제풀이 업로드

study/22.11.15/HJH/1475. 방 번호.java
`8/10 = 0`이 맞나를 한참을 고민했습니다.. 
그래서 방 번호 2시간을 풀었습니다.
제 친구가 이런 걸 모르면 뭘 공부해야하녜요
구현 문제 딱대.. && 자소서 쓰고 지원하고 시험보고 하느라 이번주도 알고리즘엔 시간을 못 쏟았습니다 😭
=> [Week36] 한지희 문제풀이 업로드

study/22.11.15/HHS/Main_BOJ_1138_한줄로서기.java, study/22.11.15/HHS/Main_BOJ_1475_방번호.java, study/22.11.15/HHS/Main_BOJ_18111_마인크래프트.java, study/22.11.15/HHS/Main_BOJ_21608_상어초등학교.java
- 알고리즘 문제 푸는거 일주일 쉬었다고 바로 감 잃어서 당황했다 (Main으로 이름 안바꾸거나 패키지 안지우고 바로 검사 돌려서 계속 틀렸다고 해서 당황쓰했네 ㅎㅎ,,)
- 다행히 구현 관련 문제들이어서 문제풀면서 감찾으려고 많이 노력했다
- 오랜만에 구현푸니까 즐거웠당
=> [Week36] 한혜성 문제풀이 업로드

study/22.11.15/HJJ/Baekjoon1138.java, study/22.11.15/HJJ/Baekjoon1475.java, study/22.11.15/HJJ/Baekjoon18111.java, study/22.11.15/HJJ/Baekjoon21608.java
풀이를 너무 어렵게 생각해서 시간이 오래걸렸습니다.
전체 시간복잡도를 계산해보니 최대 6천만정도이길래 
브루트포스로 풀이 할 수 있다는 사실을 늦게 깨닫고 풀었네요. 😅
<br>
알고리즘만 잘 설계하고 적절한 자료구조를 사용하면 어렵지 않게 풀 수 있었습니다.
하지만 구현문제이다보니 코드 작성시간이 너무 오래걸렸네요.ㅜㅜ
평소에 구현 문제연습을 해서 실전에선 빠르게 풀 수 있게 해야겠어요. 💪
<br>
뭔가 간단하면서도 풀이방법을 생각해내는 것이 어려웠습니다.
<br>
이번주 문제중에 제일 쉬웠던 것 같아요.
6과 9를 하나의 숫자로 생각하고 계산하니 쉽게 풀 수 있었습니다.
<br>
구현문제는 알고리즘적으로 큰 어려움은 없지만 
설계하고 코드로 구현하는 것이 어려운 것 같습니다.
많이 연습해서 실전해서 빨리 풀 수 있게 해야겠어요.
<br>
=> [Week36] 황정준 문제풀이 업로드

study/22.11.01/BJM/Programmers_42579.java, study/22.11.15/BJM/BOJ_1138.java, study/22.11.15/BJM/BOJ_1475.java, study/22.11.15/BJM/BOJ_18111.java, study/22.11.15/BJM/BOJ_21608.java
베스트앨범 34주차 문제 못 풀었던거 풀어서 올린 거라 무시해주세여
그리고 이번주 파일에 주석 좀 많아요. 지워서 올릴까 하다가 그냥 올렸습니당. 미안합니듀..~~~
- 방 번호
이 문제 처음에 9를 아예 6으로 바꿀 생각은 못했음 (정확히는 그렇게 해도 풀릴 줄 몰랐음ㅎ)
6과 9의 쌍 개수만큼 1세트로 카운트한 다음에 남은 개수가 짝수면 2로나눈 수를, 홀수면 2로나누고 +1 해준 수를 세트에 추가해주는 방식으로 했는데 반례 찾다가 반올림하는 방식의 풀이를 봐버렸습니다. 😗
- 한 줄로 서기
이거.. 문제 이해가 잘 안돼서 진짜 한참을 읽어봤다. 푸는 거 보다 문제 이해가 더 어려웠음
- 마인크래프트
분류에 브루트포스 알고리즘이라 써진 거 보고 풀이방법에 접근할 수 있었음 ^3^
이 문제는 제시된 예시 외에 반례로 들어오는 테케가 많아서 어느 부분에서 문제가 생기는지 찾는게 상당히 어려웠습니다. 게다가 층마다 일일이 경우의 수를 구해야 해서, 디버깅 돌릴 때도 오래걸리는게 .. 상당히 시간을 잡아 먹은 것 같아염.
- 상어 초등학교
문제 읽고 대충 어떻게 해야 할지는 감이 왔는데 뭔가 자잘한 부분들에서 까다로웠던 것 같습니다. 푸는 방법이 다양할 것 같은데, 다른 분들은 어떻게 푸셨을지 궁금하네요..~~ 클래스 객체 만든거 진짜 오바라고 생각함 .. 없어도 풀 수 있을거 같은데 그냥 당장 생각나는게 이 방법이었어요....ㅂ
일단 저는 생각했던 풀이 방식에 다행히도 논리적인 오류는 없었지만... 코드로 쓰다보니까.. 비효율적으로 풀어내야하는 부분들이 계속 생기더라구요. 그래서 진짜 이게 맞나? 싶어서 …
=> [Week36] 방지민 문제풀이 업로드

study/22.11.15/EJH/1138_한 줄로 서기.py, study/22.11.15/EJH/1475_방 번호.py, study/22.11.15/EJH/18111_마인크래프트.py, study/22.11.15/EJH/21608_상어 초등학교.py
구현은 그냥 귀찮을 뿐
구현도 익숙해지니 빠르게 풀 수 있게 되었습니다.
=> [Week36] 이정훈 문제풀이 업로드

study/22.11.22/HJH/Coins.java, study/22.11.22/HJH/망가진 키보드.java
이번 주는 또 알고리즘 현타가 왔어요.. 제가 못 하는거라서 한심방통입니다. 더 해볼게여..
=> [Week37] 한지희 문제풀이 업로드

study/22.11.22/HJJ/Baekjoon12865.java, study/22.11.22/HJJ/Baekjoon25916.java, study/22.11.22/HJJ/Baekjoon3067.java, study/22.11.22/HJJ/Baekjoon6503.java
배낭문제는 오랜만에 풀어서 점화식 세우는게 어려웠습니다. 😂
분명... 풀었던 문제인데 기억이 안나네요. 연습이 부족한거겠죠.
투포인터 문제는 알고리즘은 무난하게 작성했으나 
코드에 틀린 곳이 있어서 맞왜틀을 계속 시전하냐고 오래걸렸네요.
DP문제를 다시 연습해봐야겠다고 생각했습니다!! 마니해봐야겠어요
=> [Week37] 황정준 문제풀이 업로드

study/22.11.22/EJH/12865_평범한 배낭.py, study/22.11.22/EJH/25916_싫은데요.py, study/22.11.22/EJH/3067_Coins.py, study/22.11.22/EJH/6503_망가진 키보드.py
- 오랜만의 dp라서 처음에 많이 헷갈렸네요
- dp라도 조건에 따라서 푸는 방식이 달라졌습니다.
이번주 문제 난이도는 비슷하고 풀이도 비슷하네요
=> [Week37] 이정훈 문제풀이 업로드

study/22.11.22/BJM/BOJ_25916.java
- 싫은데요
처음에는 배열을 여러 번 돌면서 구멍 크기를 일일이 더하는 식으로 모든 크기를 구해서 최대값을 찾는 방식으로 했는데,
사실 돌리기 전에도 예상은 했지만 시간초과가 떠서..~~ ㅡ.ㅡ 위의 접근방식을 베이스로 투포인터로 풀 수 있게끔 변형했습니다..
발등에 불떨어진 일들이 많아서 한 문제밖에 못 풀었어요 ㅎ.
졸논이랑 과제 무사히 다 끝내면.. 저번에 못 푼 문제까지 싹 다 해서 오겠습니다...
=> [Week37] 방지민 문제풀이 업로드

study/22.11.22/HHS/Main_BOJ_12865_평범한배낭.java, study/22.11.22/HHS/Main_BOJ_25916_싫은데요.java, study/22.11.22/HHS/Main_BOJ_3067_coin.java, study/22.11.22/HHS/Main_BOJ_6503_망가진키보드.java
- 냅색 오랜만이어서 하나하나 디피 그리면서 생각하는게 조금 힘들었다
- 냅색 오랜만~~ 반가웠고 다신 보지 말자~
=> [Week37] 한혜성 문제풀이 업로드

study/22.11.22/PKB/Coins.java, study/22.11.22/PKB/망가진 키보드.java, study/22.11.22/PKB/싫은데요.java, study/22.11.22/PKB/평범한 배낭.java
냅색 개념부터 해서 다시 학습해보았습니다. 어렵어렵
배낭.. 냅색.. 너무 어려워요 계속 풀어보는 게 답이겠죠..? 흙흙 ,,
=> [Week37] 박기범 문제풀이 업로드

study/22.11.29/HHS/Main_BOJ_1520_내리막길.java, study/22.11.29/HHS/Main_BOJ_1535_안녕.java, study/22.11.29/HHS/Main_BOJ_1958_LCS3.java, study/22.11.29/HHS/Main_BOJ_2631_줄세우기.java
- bfs로 푸니 메모리초과가 나서 dfs로 바꿨더니 시간초과가 났다...ㅎ
- dp로 풀 필요 없을 것 같았는데 어쩔 수 없이 dp를 사용해야 할 것 같아서 결국 코드를 수정해줬다...
- 초과만 안나면 너무 쉬운 문제인데 dp로 구현해보니 색달랐다
- 문제를 몰아서 풀었더니 약간 진땀났다 담부턴 미리미리 풀어야겟다
=> [Week38] 한혜성 문제풀이 업로드

study/22.11.29/HJJ/Baekjoon1535.java, study/22.11.29/HJJ/Baekjoon1958.java, study/22.11.29/HJJ/Baekjoon2631.java
DP 점화식 생각하는게 어려웠습니다....
이번주는 일이 바빠서 다 풀진 못했네요ㅜㅜ
분명 다 풀었던 문제들의 심화문제인데 조금만 꼬아도 알고리즘이 머리에 잘 안떠오르네요.
차근차근 접근하는 연습을 많이 해야될 것 같습니다.
=> [Week38]황정준 문제풀이 업로드

study/22.11.29/EJH/1520_내리막길.py, study/22.11.29/EJH/1535_안녕.py, study/22.11.29/EJH/1958_LCS 3.py, study/22.11.29/EJH/2631_줄세우기.py
- 3차원 DP
- 이론은 알겠는데 머리 속에 그리기 힘들었습니다.
- dp 부터 bfs, 우선순위 큐 등 많은 알고리즘이 필요했습니다.
- 복합적인 문제라 푸는 방법도 여러가지 일 거 같았습니다.
dp만 푸는 문제들은 익숙해 졌는데  다른 알고리즘도 같이 쓰는 복합적인 문제들은 많이 어려웠습니다.
특히 3차원 DP는 이해하기 힘들었습니다.
=> [Week38] 이정훈 문제풀이 업로드

study/22.12.06/EJH/1339_단어 수학.py, study/22.12.06/EJH/1802_종이접기.py, study/22.12.06/EJH/4779_칸토어 집합.py, study/22.12.06/EJH/4796_캠핑.py
- 그리드 문제라 어떻게 풀어야 하는지 많이 생각해 보게 되네요
- 각 자리 수로 합하면서 풀었습니다.
분할 정복이나 그리드 알고리즘 이나 푸는 방식을 알면 쉬운데
푸는 방법을 생각하는게 어렵네요
=> [Week39] 이정훈 문제풀이 업로드

study/22.12.06/HHS/Main_BOJ_1339_단어수학.java, study/22.12.06/HHS/Main_BOJ_1802_종이접기.java, study/22.12.06/HHS/Main_BOJ_4779_칸토어집합.java, study/22.12.06/HHS/Main_BOJ_4796_캠핑.java
**- 단어수학**
- 각 단어들을 이차원 배열로 거꾸로 입력받고 (ABC라면 [0][0] = C, [0][1] = B, [0][2] = A) 
- 이차원배열을 가장 긴 자릿수들부터 돌면서 ([0][7], [1][7], [2][7] -> [0][6], [1][6], [2][6] ...)
- 각 알파벳들에게 숫자를 부여해주는 식으로 했는데 
- 해쉬맵, 해쉬셋, 우선순위큐를 다 가져다 쓰다보니 뭔가 더 간단하게 풀 방법들이 있을 것 같아서 다른 분들은 어떻게 푸셨을지 너무 궁금합니당ㅎㅎ
- 그리디가 그리디했다
=> [Week39] 한혜성 문제풀이 업로드

study/22.12.06/HJJ/Baekjoon1339.java, study/22.12.06/HJJ/Baekjoon1802.java, study/22.12.06/HJJ/Baekjoon4779.java, study/22.12.06/HJJ/Baekjoon4796.java
문제 설명이 너무 애매하게 적혀있어서
문제를 이해하는 것이 어려웠습니다. 😂
종이를 접었을 때 나타나는 패턴만 파악하면 쉽게 풀 수 있었지만
처음에 너무 단순하게 생각해서 몇 번 틀렸었네요.
이 문제는 좀 더 생각해보면 풀 수 있을 것 같은데
단순하게 완전탐색으로 접근해서 풀이했다가 시간초과가 났네요...
시간이 없어서 일단 틀린 코드를 올렸지만
다시 생각해보자면 각 알파벳마다 가중치를 정해주고 (문자열에 등장한 갯수, 자릿수가 높은 순서 등)
그 가중치에 따라 높은 숫자를 차례대로 배정해주면 될 것 같긴 합니다.
나머지 문제들은 무난하게 풀 수 있었네요.
그리디가 제일 어려운 것 같아요....
그리디도 연습을 많이 해야겠습니다.
=> [Week39]황정준 문제풀이 업로드

study/22.12.13/HHS/Main_BOJ_1946_신입사원.java, study/22.12.13/HHS/Main_BOJ_1946_신입사원2.java, study/22.12.13/HHS/Main_BOJ_20920_영단어암기는괴로워.java, study/22.12.13/HHS/Main_BOJ_2437_저울.java, study/22.12.13/HHS/프로그래머스_위장.java
**- 신입사원**
- 우선순위큐를 이용해서 풀었는데 통과는 했으나 생각보다 소요시간이 오래걸려서 배열로도 풀어보며 시간을 좀 줄여봤숩니당
- 두가지 코드 다 올릴게유
- 이번주는 문제가 대부분 수월했던 것 같네용
=> [Week40] 한혜성 문제풀이 업로드

study/22.12.13/EJH/BOJ_1946_신입_사원.java, study/22.12.13/EJH/BOJ_20920_영단어_암기는_괴로워.java, study/22.12.13/EJH/BOJ_2437_저울.java, study/22.12.13/EJH/P_위장.java
- 역시 그리드 알고리즘 생각하는게 많이 어려웠습니다.
회사에서 JAVA를 쓰니 이제 알고리즘도 JAVA로 풀려고합니다.
그 동안 파이썬으로 풀다가 JAVA로 돌아오니 많이 어색하네요
=> [Week40] 이정훈 문제풀이 업로드

study/22.12.13/HJH/위장.java
=> [Week40] 한지희 문제풀이 업로드

study/22.12.13/PKB/신입 사원.java, study/22.12.13/PKB/영단어 암기는 괴로워.java, study/22.12.13/PKB/위장.java, study/22.12.13/PKB/저울.java
- 일단 정렬은 해야 할 것 같아서 한 뒤에 어떻게 해야 할지 몰라서 찾아봤어요 ,, 근데 어떡하죠 이해가 안 돼요 ! 저 오늘 발표인데 ㅍㅍ
=> [Week40] 박기범 문제풀이 업로드

study/22.12.13/HJJ/Baekjoon1946.java, study/22.12.13/HJJ/Baekjoon20920.java, study/22.12.13/HJJ/Baekjoon2437.java, study/22.12.13/HJJ/Programmers_위장.java
해쉬문제는 풀만했지만
그리디는 생각부터가 막막했습니다. 😂😂 
인터넷의 도움을 좀 받았네요.
해쉬맵의 데이터를 Entry로 꺼내서 가공하는 연습을 할 수 있어서 좋았습니다.
그리디를 잘하려면 수학적인 생각을 잘 해야 할 것 같아요.
=> [Week40]황정준 문제풀이 업로드

study/22.12.06/BJM/BOJ_1339.java, study/22.12.13/BJM/BOJ_1946.java, study/22.12.13/BJM/BOJ_20920.java
약속 때문에 못올릴 것 같다그래서 대신 올립니다.
.
.
=> [Week40] 방지민 문제풀이 업로드

study/22.12.20/HHS/두큐합같게하기.java, study/22.12.20/HHS/성격유형검사하기.java
**- 두 큐 합 같게 하기**
- 시간초과가 계속 나서 60만 번 와일문을 돌렸을 때도 해결이 안된다면 바로 빠져나오게 구현하니 겨우 풀렸습니당,,
**- 성격 유형 검사하기**
- 쉬운 문제인데 코드가 계속 반복되어서 사실 이게 좋은 풀이인건지 확신이 안섭니다...
- 방학을 맞이하여 여행 준비를 하고 있어서 시간이 마땅치 않아 문제를 다 못풀었습니당
- 다녀오고나서 부지런히 풀어볼게요 이번주도 화이팅!
=> [Week41] 한혜성 문제풀이 업로드

README.md, study/22.12.20/EJH/P_두_큐_합_같게_만들기.java, study/22.12.20/EJH/P_등산코스_정하기.java, study/22.12.20/EJH/P_성격_유형_검사_하기.java, study/22.12.20/EJH/P_코딩_테스트_공부.java
- 효율성 테스트 때문에 예외 처리 하는 방법을 많이 생각하게 되었네요
- 테스트 조건에서 안되는 조건들 찾아서 해결하는게 힘들었습니다.
- 그래프에 조건을 추가해서 계산해야 해서 힘들었습니다.
자바로 풀어서 그런지 알고리즘 짜는게 많이 귀찮게 느껴지는 문제들 이었습니다.
=> [Week41] 이정훈 문제풀이 업로드

study/22.12.20/BJM/Programmers_118666.java, study/22.12.20/BJM/Programmers_118667.java, study/22.12.20/BJM/Programmers_118669.java
- 등산코스 정하기
무슨 알고리즘을 변형해야 하는진 알겠는데 .. 뭔가 총체적으로 이해하기가 어려웠다..
1, 2번은 다른 때 코테문제보다 비교적 쉽게 나온거같음
내가 별다른 풀이참고 없이 한 번에 맞았으면 남들한테는 발로 풀 수 있는 수준이기 때문
(지금까지 카카오 코테 두 번 봤는데 전부 1번 문제도 다 못풀고 그냥 나왔었음ㅜ)
=> [Week41] 방지민 문제풀이 업로드

study/22.12.20/PKB/두 큐 합 같게 만들기.java, study/22.12.20/PKB/성격 유형 검사하기.java
등산코스 너무 어려워요 ,,
등산코스 이해가 잘 안 되는 부분이 있고, 두 문제만 풀었슴다.. 담주 스터디 전까지 마저 풀게요 ,,
=> [Week41] 박기범 문제풀이 업로드

study/22.12.17/HJH/두큐합같게만들기.js, study/22.12.17/HJH/등산코스 정하기.js, study/22.12.17/HJH/성격유형검사하기.js
자바스크립트로 풀려고 하니 너무 부담되네요..
`두 큐 합 같게 만들기`도 자바스크립트로 풀어보려고 했는데요,
배열을 큐 처럼 사용해서 머리를 열심히 굴려봤는데 런타임에러가 납니다. (오 2개 맞았어요)
역시.. 하던 자바로 해야하는걸까요.. ㅠ
`등산코스 정하기` ㅂㄷㅂㄷ
=> [Week41] 한지희 문제풀이 업로드

study/22.12.27/BJM/BOJ_1676.java, study/22.12.27/BJM/BOJ_17175.java, study/22.12.27/BJM/BOJ_1915.java
- 팩토리얼 0의 개수
일단 문제 이해부터 어려웠고, 수학에 많이 약해서 이게 되나.. 싶은 심정으로 풀었습니다.
- 가장 큰 정사각형
DP배열에 왜 테두리가 필요한지 아직도 궁금하네요
원본배열의 (0,0)부분을 계산하기 위해서라는건 아는데, 어짜피 DP배열의 첫열과 첫행은 원본배열과 똑같이 채워질거라고 생각해서 똑같이 넣고 (1,1)부터 계산하면 되지 않나싶었는데 테케 통과가 안되더라구여.
반례는 못찾았지만 있으니까 통과가 안되는거겠죠?? 🤔
아직 마지막 문제는 못풀었지만 최대한 생각해보겠습니다잇
점점 당주에 못푸는 문제들이 늘어나고있는데 언제쯤 업보청산할수있을지...
=> [Week42] 방지민 문제풀이 업로드

study/22.12.27/EJH/BOJ_1162_도로포장.java, study/22.12.27/EJH/BOJ_1676_팩토리얼_0의_개수.java, study/22.12.27/EJH/BOJ_17175_피보나치는_지겨웡.java, study/22.12.27/EJH/BOJ_1915_가장_큰_정사각형.java
=> [Week42] 이정훈 문제풀이 업로드

study/22.12.27/HJJ/Baekjoon1162.java, study/22.12.27/HJJ/Baekjoon1676.java, study/22.12.27/HJJ/Baekjoon17175.java, study/22.12.27/HJJ/Baekjoon1915.java
=> [Week42] 황정준 문제풀이 업로드

study/2023/23.01.03/BJM/BOJ_1094.java
=> [Week43] 방지민 문제풀이 업로드

README.md, study/2023/23.01.03/EJH/BOJ_1002_터렛.java, study/2023/23.01.03/EJH/BOJ_1094_막대기.java, study/2023/23.01.03/EJH/BOJ_1591.java, study/2023/23.01.03/EJH/BOJ_1629_곱셈.java
수학적 지식이 기반이 되어야 풀 수 있는 문제들이 있어서 어려웠음
- 두 원의 관계에 관해서 알고 있어야 가능했음
- 모듈러 성질을 알고있어야 가능했음
일반적인 알고리즘이 아니라 수학적 지식을 통한 알고리즘 문제들은 기반 지식이 필요하지만 더 빠르게 문제를 풀 수 있다.
그리드에서 중요
=> [Week43] 이정훈 문제풀이 업로드

study/2023/23.01.03/HJH/1029. 곱셈.js, study/2023/23.01.03/HJH/1094. 막대기.js
백준에서 자바스크립트로 문제 풀어봤는데 자꾸 틀렸다고 나와서 시간을 많이 허비했네요..
=> [Week43] 한지희 문제풀이 업로드

study/2023/23.01.03/HHS/Main_BOJ_1002_터렛.java, study/2023/23.01.03/HHS/Main_BOJ_1094_막대기.java
- 수학문제라 즐겁게 두 문제 풀고 나머지는 연수원에서 풀려고 했었는데 제가 생각한 것보다 연수원에서 시간내기가 힘들 것 같습니다...나머지는 연수원 다녀온 이후에 풀어놓겠습니다!
- 제가 8시에 아무말없이 스터디에 들어오지 않더라도 그냥 진행해주세요,,,들어갈 수 있는 상황이 된다면 들어가겠지만 오늘도 시간가는줄 모르고 하루가 끝나서 내일 되어야 상황을 알 수 있을 것 같습니다
=> [Week43] 한혜성 문제풀이 업로드

study/2023/23.01.03/HJJ/Baekjoon1002.java, study/2023/23.01.03/HJJ/Baekjoon1094.java, study/2023/23.01.03/HJJ/Baekjoon1629.java
수학적 지식이 필요한 문제가 많아서 생각보다 어려웠습니다.
수학적 사고도 할 수 있도록 연습해야겠어요.
다풀고나서 작성하겠습니다.
=> [Week43]황정준 문제풀이 업로드

study/2022/22.12.20/PKB/등산코스 정하기.java, study/2022/22.12.27/PKB/가장 큰 정사각형.java, study/2022/22.12.27/PKB/도로포장.java, study/2022/22.12.27/PKB/팩토리얼 0의 개수.java, study/2022/22.12.27/PKB/피보나치는 지겨웡~.java, study/2023/23.01.03/PKB/1002. 터렛.java, study/2023/23.01.03/PKB/1094. 막대기.java, study/2023/23.01.03/PKB/1629. 곱셈.java
수학 너무 어려워요.......
계속 찾아보면서 했네요 ,,
=> [Week43] 박기범 문제풀이 업로드

study/2023/23.01.10/HJJ/Baekjoon26257.java, study/2023/23.01.10/HJJ/Baekjoon26258.java, study/2023/23.01.10/HJJ/Baekjoon26259.java, study/2023/23.01.10/HJJ/Baekjoon26260.java
std 문제랑 다중 일차 함수는 풀만했지만 백룸 문제가 꽤 어려웠습니다.
백룸은 2차원 DP로 식을 짜고 벽이 있는 경우는 제외하면서 점화식 계산을 하도록 했고
마지막방에 도착할 수 없는 경우는 미리 판단하도록 했는데 계속 틀렸다고 나오네요.... 맞왜틀....
이가 빠진 이진트리는 처음에 접근을 잘못해서 아직 다 못풀었습니다.
개념자체는 어렵진 않은데 생각보다 조건을 잘 생각해야되는 문제들이었습니다.
코테문제다워요.
=> [Week44] 황정준 문제풀이 업로드

study/2023/23.01.10/EJH/BOJ_26257_std_shared_ptr.java, study/2023/23.01.10/EJH/BOJ_26258_다중_일차_함수.java, study/2023/23.01.10/EJH/BOJ_26260_이가_빠진_이진_트리.java
문제가 전부 기존에 풀던 방식과는 많이 달라 어려웠음
바빠서 1문제는 못풀었네 2주였는데...
=> [Week44] 이정훈 문제풀이 업로드

study/2023/23.01.17/BJM/BOJ_26257.java, study/2023/23.01.17/BJM/BOJ_26258.java, study/2023/23.01.17/BJM/BOJ_26260.java
- 다중 일차 함수
자꾸 시간초과 나서 이분 검색 조건문을 바꿔줬다.. 찾아내느라 애먹었다.
- 이가 빠진 이진 트리
트리를 아예 구현하고 후위 순회하는 방식으로 하려했는데, 출력값이 이상했다. (그냥 이진탐색트리가 구현돼서 트리 높이가 안맞았던거같음) 그래서 아예 배열에 정렬하고 규칙 찾아서 재귀돌렸다.
메모리랑 시간 엄청 잡아먹는 이유를 알았다. 다음에는 StringBuilder를 애용해보겠음
반례 케이스도 없고 다른사람 풀이도 없어서 어마무시하다.
=> [Week44] 방지민 문제풀이 업로드

study/2023/23.01.10/HJH/std::shared_ptr.java, study/2023/23.01.10/HJH/다중 일차 함수.java, study/2023/23.01.10/HJH/이가 빠진 이진 트리.java
모르겠어요
몰라서 잘 못 풀겠는데 참고할 수도 없어서 답답했네요 ,,
발표자라 부담감도 크고...
=> [Week44] 한지희 문제풀이 업로드

study/2023/23.01.10/PKB/std::shared_ptr.java, study/2023/23.01.10/PKB/다중 일차 함수.java, study/2023/23.01.10/PKB/이가 빠진 이진 트리.java
푸는 게 너무 어려웠어요 ,,
백룸 어떻게 풀어야 하죠...?
=> [Week44] 박기범 문제풀이 업로드

study/2023/23.01.10/HHS/Main_BOJ_26257_std_shared_ptr.java, study/2023/23.01.10/HHS/Main_BOJ_26258_다중일차함수.java
**다중일차함수**
- 시간초과가 나서 일단 더이상 고치지 못하고 일단 제출하였습니다. 오랜만에 푸니 감이 잘 안 잡혀서 진땀났네요
- 연수원 생활이 끝나고 자유를 찾게 되면 바로 나머지 문제들을 풀어보겠습니다.
=> [Week44] 한혜성 문제풀이 업로드

study/2023/23.01.31/BJM/Programmers_42583.java, study/2023/23.01.31/BJM/Programmers_42840.java, study/2023/23.01.31/BJM/Programmers_43162.java
=> [Week45] 방지민 문제풀이 업로드

study/2023/23.01.31/HHS/네트워크.java, study/2023/23.01.31/HHS/다리를지나는트럭.java, study/2023/23.01.31/HHS/단속카메라.java, study/2023/23.01.31/HHS/모의고사.java
- 정말 오랜만에 푸는 문제들이라 시간이 더 걸렸습니다.
- 하지만 생각해서 풀다보면 그리 어려운 문제는 아니었던 것 같습니다.
- 기강잡아~
=> [Week45] 한혜성 문제풀이 업로드

study/2023/23.01.31/HJJ/Programmers_네트워크.java, study/2023/23.01.31/HJJ/Programmers_다리를지나는트럭.java, study/2023/23.01.31/HJJ/Programmers_단속카메라.java, study/2023/23.01.31/HJJ/Programmers_모의고사.java
단속카메라문제는 해결법을 찾는데 시간이 많이 걸렸네요.
역시 그리디 문제는 어렵습니다.
나머지 문제는 무난한 편이었네요.
오랜만에 프로그래머스 문제를 푸니깐 코딩테스트보는 느낌이 나서 좋았습니다.
긴장감을 늦추지 말아야겠어요.
=> [Week45] 황정준 문제풀이 업로드

study/2023/23.01.31/EJH/P_네트워크.java, study/2023/23.01.31/EJH/P_다리를_지나는_트럭.java, study/2023/23.01.31/EJH/P_단속카메라.java, study/2023/23.01.31/EJH/P_모의고사.java
=> [Week45] 이정훈 문제풀이 업로드

study/2023/23.02.07/BJM/Programmers_1844.java, study/2023/23.02.07/BJM/Programmers_77484.java, study/2023/23.02.07/BJM/Programmers_86491.java
- 게임 맵 최단거리
bfs 개념을 다시 공부하느라 시간을 쓴 듯
문제 자체는 상하좌우 살피는 문제라 이전에도 풀었던 이력이 있어서 크게 어렵지 않았음
- 최소직사각형
풀이의 핵심이 떠오르면 그 이후로는 엄청 쉬운데 여기까지 도달하는게 케바케인듯? 멘붕...
모루게써염
=> [Week46] 방지민 문제풀이 업로드

study/2023/23.02.07/HJJ/Programmers_게임맵최단거리.java, study/2023/23.02.07/HJJ/Programmers_로또의최고순위와최저순위.java, study/2023/23.02.07/HJJ/Programmers_징검다리.java, study/2023/23.02.07/HJJ/Programmers_최소직사각형.java
징검다리가 알고리즘을 생각해내는데 어려웠다... 결국 해설을 참고했네요.😥
그다음으로는 최소직사각형이 생각보다 오래걸렸는데
이해하면 금방풀 수 있는 문제였지만... 너무 어렵게 생각해서 오래걸린 것 같습니다.
나머지 문제는 무난했습니다.
이분탐색 문제는 뭔가 이분탐색과 거리가 있어보이는 문제를 이분탐색으로 전환해서 생각하는 것이 많이 어려운 것 같습니다. 
새로운 유형의 이분탐색 문제가 나오면 애를 먹게되네요.
더 많은 연습이 필요할 것 같아요.
=> [Week46] 황정준 문제풀이 업로드

study/2023/23.02.07/HJH/게임 맵 최단거리.js, study/2023/23.02.07/HJH/로또의 최고 순위와 최저 순위.js, study/2023/23.02.07/HJH/징검다리.js, study/2023/23.02.07/HJH/최소직사각형.js
=> [Week46] 한지희 문제풀이 업로드

study/2023/23.02.07/HHS/게임 맵 최단거리.java, study/2023/23.02.07/HHS/로또의 최고순위와 최저순위.java
=> [Week46] 한혜성 문제풀이 업로드

study/2023/23.02.07/PKB/로또의 최고 순위와 최저 순위.java
=> [Week46] 박기범 문제풀이 업로드

study/2023/23.02.14/HJJ/Leetcode_238.java, study/2023/23.02.14/HJJ/Leetcode_347.java, study/2023/23.02.14/HJJ/Leetcode_44.java, study/2023/23.02.14/HJJ/Leetcode_49.java
Product of Array Except Self 문제와 Wildcard Matching 문제가 어려웠습니다.
Product of Array Except Self는 코드자체는 간단했지만 개념을 떠올리는게 조금 어려웠고
Wildcard Matching는 DP를 이용해서 풀이하는 것이 어려웠네요.
나머지 문제는 무난했습니다.
영어문제는 오랜만에 풀어보는데 코테에서 외국 플랫폼으로 보는 경우도 있으니 영어문제도 연습해두면 좋을 것 같습니다.
DP는 연습만이 살길이라는 것을 다시 느꼈습니다.
=> [Week47] 황정준 문제풀이 업로드

study/2023/23.02.14/EJH/Group_Anagrams.java, study/2023/23.02.14/EJH/Product_of_Array_Except_Self.java, study/2023/23.02.14/EJH/Top_K_Frequent_Elements.java
=> [Week47] 이정훈 문제풀이 업로드

study/2023/23.02.14/BJM/LeetCode_238.java, study/2023/23.02.14/BJM/LeetCode_347.java, study/2023/23.02.14/BJM/LeetCode_49.java
- Product of Array Except Self
처음에 이중for문 돌렸다가 테케 안넘어가서 봤는데 지문에 O(n)으로 해결하라고 하더라....
그래서 결국 솔루션을 봤는데 정방향으로 계산 후 역방향으로 다시 곱하면서 돌아오는 솔루션이 있었다.
잘 이해가 안돼서 손으로 직접 그려봤는데 아직도 '이게 왜 되지..?' 라는 생각이듦... 뭔가 확실하게 이해가 안돼서 답답하네요 ㅎ.
- Group Anagrams
해결법이 떠오른다 해도 내장 메소드들을 더 잘 알고있으면 쉽게 풀 수 있고 .. 아니면 돌아돌아 간다는 사실을 새삼 느낌.
이거 풀면서 처음 안 사실들이 몇 개 있었다.
하나는 char 배열을 new String()의 인자로 넘겨서 문자열을 생성할 수도 있다는 점 (toCharArray가 있으니 당연히 반대도 있을텐데....아무튼 몰랐음)
그 다음은 해시맵 내장 함수 map.values()의 존재 자체랑, 반환값이 Collection 형태여서 List에 바로 넣을 수 있다는 점....
그런데 반환값에 new ArrayList<>(map.values())를 쓰는 건 되는데..
왜 미리 리스트를 만들어놓고 list.add(map.values())를 쓸 수는 없는 건지...잘... 모르겠네..???
오, 어려움
=> [Week47] 방지민 문제풀이 업로드

study/2023/23.02.28/HJJ/Baekjoon1325.java, study/2023/23.02.28/HJJ/Baekjoon14430.java, study/2023/23.02.28/HJJ/Baekjoon20055.java, study/2023/23.02.28/HJJ/Baekjoon2583.java
효율적인 해킹 문제가 생각보다 오래걸렸습니다.
시간복잡도 고려해서 DP로 접근해서 풀어야하나 생각했는데 잘안풀려서 그냥 BFS돌리니 되더라구요...
시간은 오래걸리지만 통과는 됩니다.
컨베이어벨트는 아직 못풀었네요. 나머지 문제는 무난했습니다.
추측으로 문제풀이 방법만 고민하지말고 일단 나이브하게 접근하면서 개선시키는게 좋다는 생각이 들었습니다.
=> [Week48] 황정준 문제풀이 업로드

study/2023/23.02.28/BJM/BOJ_1325.java, study/2023/23.02.28/BJM/BOJ_14430.java, study/2023/23.02.28/BJM/BOJ_2583.java
- 효율적인 해킹
dfs로 풀었다가 시간초과 나서 bfs로 후다닥 바꿈. 근데 어찌저찌하면 bfs도 모든 노드를 돌지 않게끔 할 수 있을 거 같은데 지금으로선 잘 모르겠군요.! 나중에 함 해보겠음.
- 영역 구하기
푸는 방법 자체는 생각하기 쉬운데 2차원배열 가지고  좌표평면에다 사각형을 어떻게 그리나 생각좀 많이 했음.. 결국 똑같이 그리는 건 포기하고 왜 이렇게 그려지는지에 대해서 이해를 하는데 시간썼읍니다. 나머지는 그냥 여느 dfs문제랑 다를바 없어서 어렵진 않았당.
담주까진 4번 풀겠지 ..
=> [Week48] 방지민 문제풀이 업로드

study/2023/23.03.14/EJH/P_160585.java, study/2023/23.03.14/EJH/P_161988.java, study/2023/23.03.14/EJH/P_161989.java, study/2023/23.03.14/EJH/P_161990.java
> PR이 처음이라면 [WIKI](https://github.com/ssafy6-nathan/algorithm-study/wiki/Git-Convention) 내용 확인!!
>
> PR 제목 양식 - `[WeekNN] 홍길동 문제풀이 업로드` (ex - [Week32] 황정준 문제풀이 업로드)
=> [Week49] 이정훈 문제풀이 업로드

study/2023/23.02.28/BJM/BOJ_20055.java, study/2023/23.03.14/BJM/Programmers_160585.java, study/2023/23.03.14/BJM/Programmers_161988.java, study/2023/23.03.14/BJM/Programmers_161989.java, study/2023/23.03.14/BJM/Programmers_161990.java
- 혼자서 하는 틱택토
조건 찾기가 너무 힘들다. 그래서 사람들이 올려놓은 조건 보고 했는데도 안되길래 애먹었는데 빙고개수 구하는 부분이 틀린거였음 ㄱ-
1, 2번은 상대적으로 무난하게 풀림
다 풀면 pr수정하게뜸니다.~
=> [Week49] 방지민 문제풀이 업로드

study/2023/23.03.14/HJJ/Programmers_덧칠하기.java, study/2023/23.03.14/HJJ/Programmers_바탕화면정리.java, study/2023/23.03.14/HJJ/Programmers_연속펄스부분수열의합.java, study/2023/23.03.14/HJJ/Programmers_혼자서하는틱택토.java
혼자서 하는 틱택토 문제의 조건을 모두 찾아내는 것이 생각보다 어려웠습니다.
연속 펄스 부분 수열의 합은 아직 못풀어서 풀면 추가해두겠습니다.
특정 알고리즘이 쓰이지 않아도 구현만으로도 머리아픈 문제가 생각보다 있다는 걸 다시 깨달았습니다.
=> [Week49] 황정준 문제풀이 업로드

study/2023/23.03.28/BJM/Programmers_159993.java, study/2023/23.03.28/BJM/Programmers_159994.java
1, 2번 둘 다 어떤식으로 풀어야 할 지는 빠르게 생각이 났는데 디테일한 처리를 생각해내는 건 조금 시간이 걸렸웁니다..~
카드 뭉치의 경우는 goal을 만들 수 없는 조건을 어떻게 판별해야하는지 고민했습니당.
(처음엔 count 변수를 써서 일치하지 않는 횟수를 셌는데, 마지막 테케가 통과가 안돼서 보니 굳이 카운팅 할 필요가 없단 걸 깨달음 ㅎ)
미로 탈출의 경우는 딱봐도 사방탐색 + dfs/bfs 문제인 건 알았지만 (1) 출발 -> 레버 -> 도착 순으로 거쳐야되고 (2) 왔던 길로 또 갈 수 있다는 조건이 있어서 쪼금 헷갈렸네요. 살짝 도움받았지만 이해하기 어려운 문제는 아니었음.
미로 형식의 문제는 bfs를 쓰는거라고 항상 풀 때마다 이야기하는데 자꾸 잊어먹어요. 조금만 생각해보면 왜 bfs를 쓰는게 효율적인지 알 수 있는데.. 생각하는 힘을 기릅시다 ..~~
나머지는 일정때문에 풀 수 있을지 모르겠지만 노력해보겠습니당.
=> [Week50] 방지민 문제풀이 업로드

study/2023/23.03.28/HJH/리코쳇로봇.js, study/2023/23.03.28/HJH/카드뭉치.js
자바스크립트로 알고리즘 문제 풀 때 입력 받을 때가 가장 고민됩니다..
근데 또 다른 분들 코드 보니까 자바스크립트로 푼 풀이 길이가 되게 짧을 때가 또 있네요.. 자바하다가 자스로 하니까 짧을수록 더 많은 걸 압축해놓은 기분입니다..
=> [Week50] 한지희 문제풀이 업로드

study/2023/23.03.28/HJJ/Programmers_당구연습.java, study/2023/23.03.28/HJJ/Programmers_미로탈출.java, study/2023/23.03.28/HJJ/Programmers_카드뭉치.java
당구 연습 문제에서 최소거리를 생각하는 것이 어려웠습니다.
수학적 지식으로 타겟 좌표를 상하좌우 점대칭 시켜서 계산한 거리중에 최소값을 찾았지만 여기까지 도달하는데 오래걸렸네요.
생각하는 힘을 많이 길러야겠습니다.
짧은 시간안에 해법을 도출해서 코드로 작성하는게 아직도 어렵네요
=> [Week50] 황정준 문제풀이 업로드

study/2023/23.04.04/HJH/선긋기.js, study/2023/23.04.04/HJH/센서.js, study/2023/23.04.04/HJH/좌표압축.js, study/2023/23.04.04/HJH/파일정리.js
=> [Week51] 한지희 문제풀이 업로드

study/2023/23.04.04/BJM/BOJ_18870.java, study/2023/23.04.04/BJM/BOJ_20291.java
트리맵! 처음써봤다! 1,2번 문제는 버퍼로 출력하든 StringBuilder 쓰든 메모리랑 시간에서 별 차이 없더란다... 그래도 StringBuilder가 좀 더 빠를 줄 알았는디.. 아무튼 메모리랑 시간 엄청 잡아먹어서 좀 더 효율적이 방법이 있을 것 같은데 잘 모르겠네요.
=>  [Week51] 방지민 문제풀이 업로드

study/2023/23.04.11/HJJ/Programmers_공원산책.java, study/2023/23.04.11/HJJ/Programmers_과제진행하기.java, study/2023/23.04.11/HJJ/Programmers_광물캐기.java, study/2023/23.04.11/HJJ/Programmers_추억점수.java
광물캐기 문제는 그리디로 풀었는데 해법을 생각하는게 오래걸렸습니다...
나머진 무난했지만 과제 진행하기문제는 구현이라서 예외처리가 좀 까다로웠네요.
그리디랑 구현은 많이 풀어야 될 것 같습니다.
=> [Week52] 황정준 문제풀이 업로드

study/2023/23.04.04/BJM/BOJ_2170.java, study/2023/23.04.11/BJM/Programmers_176963.java
=> [Week52] 방지민 문제풀이 업로드

study/2023/23.04.18/BJM/Programmers_144854.sql
sql 너무 오랜만이라 문법기억이 잘 안났는데 제일 쉬워서 먼저 풀었슴다
=> [Week53] 방지민 문제풀이 업로드

study/2023/23.04.25/HJJ/Baekjoon1244.java, study/2023/23.04.25/HJJ/Baekjoon1783.java, study/2023/23.04.25/HJJ/Baekjoon20437.java, study/2023/23.04.25/HJJ/Baekjoon9996.java
앞의 세문제는 무난했고 마지막 문제인 문자열 게임 2는 최적화해서 푸는 방법을 생각하는게 어려웠습니다.
처음엔 슬라이딩 윈도우로 풀려고 했는데
가장 짧은 연속 문자열의 길이 따로 구하고 가장 긴 연속 문자열 길이를 따로 구하는 방법 밖에 생각이 안나서 이대로 풀다가 잘되더라구요...
그래서 조금 찾아보고 입력받은 문자열의 알파벳 갯수를 세주고 앞에서부터 탐색하면서 알파벳 갯수를 줄여나가며 최적화 하는 방식으로 풀이했습니다.
시간만 있으면 충분히 풀 수 있는데 빠르게 풀이하는 법을 연습해야겠어요...
=> [Week54] 황정준 문제풀이 업로드

study/2023/23.04.25/BJM/BOJ_1244.java, study/2023/23.04.25/BJM/BOJ_1783.java, study/2023/23.04.25/BJM/BOJ_20437.java, study/2023/23.04.25/BJM/BOJ_9996.java
- 병든 나이트
이 문제 제가 가져온 문제인데 (나름 쉬울 줄알고 가져온건뎅..) 티어랑 정답률보고 속았슴...
분기되는 조건을 확실히 체크하고 한 번 코드를 짜놓으면 반례로 걸리는 테스트케이스가 거의 없어서 정답률이 높은 것 같습니다.
그런데 애초에 풀이 방법에 접근하는거 자체가 제겐 너무 어려웠다네요 .... 수식으로 한 번에 답을 구할 수 있는 문제에 매우 취약한 편 ^^; 그래서 블로그 포스팅 풀이들도 보고 여러모로 도움을 많이 받아서 푼 문제였습니다. ㅠ
- 문자열 게임 2
3,4번 두 조건을 별개로 생각하면 안된다는 사실을 알아채는 것부터 고난이었습니다... 한마디로 문제 이해부터 어려웠어요. 이 문제도 도움 많이 받았습니다..!!
알고리즘 분류에 슬라이딩 윈도우 있던데 이 방법으로 푸는 방식은 생각이 전혀 안나더군여. 투포인터로 풀었습미다.
구현 문제는 특별한 알고리즘이 필요하지 않고 시키는대로 작성하면 풀려서 푸는 것 자체는 어렵지 않지만, 정신 안차리면 사소한 코드에서 오류가 나게 되고 그 오류 찾기도 여간 힘든 게 아니라서 방심할 수가 없는 것 같습니당....  어렵지 않은데 최적화가 힘들고 빨리 푸는 게 힘들어요 ㅠ_ㅠ
=> [Week54] 방지민 문제풀이 업로드

study/2023/23.05.09/BJM/Programmers_178871.java
=> [Week55] 방지민 문제풀이 업로드

study/2023/23.05.16/HJJ/Baekjoon1213.java, study/2023/23.05.16/HJJ/Baekjoon17413.java, study/2023/23.05.16/HJJ/Baekjoon2108.java, study/2023/23.05.16/HJJ/Baekjoon7568.java
이번주는 크게 어려웠던 문제는 없던 것 같습니다.
무난했지만 빨리 풀지는 못했네요...
빨리푸는 법을 좀 더 연습해야겠어요.
=> [Week56] 황정준 문제풀이 업로드

study/2023/23.05.16/PKB/단어 뒤집기 2.java, study/2023/23.05.16/PKB/덩치.java, study/2023/23.05.16/PKB/통계학.java, study/2023/23.05.16/PKB/팰린드롬 만들기.java
오랜만에 하다 보니 낯설어요
다시 익숙해져야겠습니다 알고리즘 ,,
=> [Week56] 박기범 문제풀이 업로드

study/2023/23.05.16/BJM/BOJ_1213.java, study/2023/23.05.16/BJM/BOJ_17413.java, study/2023/23.05.16/BJM/BOJ_2108.java, study/2023/23.05.16/BJM/BOJ_7586.java
- 단어 뒤집기 2
좀 비효율적으로 푼 거 같아서 찝찝... 코드가 중복되는 부분이 많은데 최적화 연습이 필요할 것 같아요.
- 팰린드롬 만들기
반례가 나올만한 부분이 어디인지 알아내는 것도 쉽지않네여...
- 통계학
해시맵 정렬은 여러 번 한 것 같은데도 헷갈려요.ㅠㅠ 연습연습
내가 다  풀었다  == 쉬운 문제들이다
=> [Week56] 방지민 문제풀이 업로드

study/2023/23.05.23/HJH/덩치.js, study/2023/23.05.23/HJH/덩치_처음짠코드.js, study/2023/23.05.30/HJH/개인정보수집유효기간.js
=> [Week57] 한지희 문제풀이 업로드

study/2023/23.06.13/HJH/생태학.js
=> [WeekN58] 한지희 문제풀이 업로드

study/2023/23.04.25/EJH/BOJ_1244.java, study/2023/23.06.13/EJH/14888.py, study/2023/23.06.13/EJH/BOJ_4358.java
=> [Week58] 이정훈 문제풀이 업로드

study/2023/23.06.13/BJM/BOJ_14888.java, study/2023/23.06.13/BJM/BOJ_2644.java, study/2023/23.06.13/BJM/BOJ_4358.java
한 주 미뤘는데 다 못 풀었네요 죄송합니다잇
푼 데 까지만 발표하께요.
=> [Week58] 방지민 문제풀이 업로드

study/2023/23.06.27/HJH/A → B.js, study/2023/23.07.04/HJH/문서 검색.js, study/2023/23.07.04/HJH/안전 영역.js, study/2023/23.07.04/HJH/접두사.js, study/2023/23.07.04/HJH/추월.js
=> [Week59-60] 한지희 문제풀이 업로드

study/2023/23.06.27/PKB/A → B.java
=> [Week59] 박기범 문제풀이 업로드

study/2023/23.07.04/BJM/BOJ_1543.java
=> [Week60] 방지민 문제풀이 업로드

study/2023/23.07.18/BJM/Programmers_82612.java
=> [Week61] 방지민 문제풀이 업로드

study/2023/23.07.25/HJJ/Programmers_둘만의암호.java, study/2023/23.07.25/HJJ/Programmers_음양더하기.java, study/2023/23.07.25/HJJ/Programmers_피로도.java, study/2023/23.07.25/HJJ/Programmers_할인행사.java
=> [Week62] 황정준 문제풀이 업로드

study/2023/23.07.25/BJM/Programmers_131127.java, study/2023/23.07.25/BJM/Programmers_155652.java, study/2023/23.07.25/BJM/Programmers_76501.java, study/2023/23.07.25/BJM/Programmers_87946.java
dfs는 그렇게나 풀었는데도 로직짜는게 헷갈림
당연함 ... 잊을만하면 풀기 때문
오랜만에 다 품
당연함 2주나 미뤘음 죄송합니다!!!!
=> [Week62] 방지민 문제풀이 업로드

study/2023/23.08.22/HJJ/Baekjoon1018.java, study/2023/23.08.22/HJJ/Baekjoon1406.java, study/2023/23.08.22/HJJ/Baekjoon15904.java, study/2023/23.08.22/HJJ/Baekjoon3986.java
이번주는 무난했습니다.
좋은 단어 문제는 생각만 잘하면 금방 풀 수 있는 문제였는데 방향을 잘못잡아서 생각보다 오래걸렸네요...
생각하는 연습을 좀더 해야겠어요.
=> [Week63] 황정준 문제풀이 업로드

study/2023/23.08.29/HJJ/Goorm195688.java, study/2023/23.08.29/HJJ/Goorm195689.java, study/2023/23.08.29/HJJ/Goorm195690.java, study/2023/23.08.29/HJJ/Goorm195691.java
무난했지만 문자열 나누기는 완전탐색하는 코드가 생각 안나서 당황스러웠네요.
계속 푸는 연습해야 바로바로 떠오를 거 같아요
구름 문제는 처음푸는거 같은데 생각보다 괜찮았습니다.
=> [Week64] 황정준 문제풀이 업로드

study/2023/23.08.29/PKB/구름 찾기 깃발.java, study/2023/23.08.29/PKB/문자열 나누기.java, study/2023/23.08.29/PKB/통증.java, study/2023/23.08.29/PKB/폭탄 구현하기 (2).java
=> [Week64] 박기범 문제풀이 업로드

study/2023/23.09.19/HJJ/Goorm195683.java, study/2023/23.09.19/HJJ/Goorm195684.java, study/2023/23.09.19/HJJ/Goorm195685.java, study/2023/23.09.19/HJJ/Goorm195686.java
=> [Week65] 황정준 문제풀이 업로드
